Checkpoint 2
dimatveev/BankSystem pull request #2
Opened 2024-04-07 17:58 UTC by dimatveev

2024-04-15 21:44 UTC, ArtemyBobkov requested changes
Библиотека с utilspp - явно лишняя. Поправьте ситуацию с фабриками, они кажется не выполняют свою функцию, и какая-то фигня со структурами вместо классов... Пересмотрите нейминг, он какой-то плавающий везде
А ещё у вас и в первой, и во второй итерациях проблемы с конфликтами, тоже надо решить

2024-04-15 21:44 UTC, ArtemyBobkov commented on AbstractFactory.cpp
> +//функции создающие счета
И где же они? Всё закомменчено...

2024-04-15 21:44 UTC, ArtemyBobkov commented on AbstractFactory.h
> +struct AbstractFactory {
Почему структура? + Абстрактная фабрика должна иметь какие-то методы создания

2024-04-15 21:44 UTC, ArtemyBobkov commented on Account.cpp
> +  if (type_of_bill == -1) {
лучше назвать константы или сделать enum

2024-04-15 21:44 UTC, ArtemyBobkov commented on Account.cpp
> +    std::cout << "Создан депозитный счёт" << std::endl;
Счёт ещё не создан в момент вывода текста. Во-первых обман пользователя по времени (что в целом приемлемо), во-вторых могут быть проблемы с тем, что что-то дальше крашнется, а пользователь будет уверен, что счёт создался

2024-04-15 21:44 UTC, ArtemyBobkov commented on Account.cpp
> +/*
Гигантские закомментированные строки не должны попадать в итоговое ревью

2024-04-15 21:44 UTC, ArtemyBobkov commented on Account.h
> +struct Account {
Да почему везде структуры-то? У вас точно не должны быть все поля и методы публичными

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +  file.open("bd_bills.csv", std::ofstream::app);
Вынести в отдельную статическую константу имя файла

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +}
Наследование передаёт привет - это всё можно сделать при помощи одной функции, принимающей базовый класс

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +  file.open("bd_accounts.csv", std::ofstream::app);
тоже в статические константы

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +    for (int i = 0; i < 4; i++) {
почему 4?

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +    std::vector<std::string> undervec;
непонятное имя переменной

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +    for (int i = 0; i < 7; i++) {
а 7 почему?)

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +}
Зачем делать три одинаковых функции, которые отличаются одной строкой, если можно сделать одну функцию, принимающую аргумент?

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +  } else if (type_of_bill == 0) {
else по сути не нужны, можно просто ифами обойтись
Да и в целом с енамом, который вы сделаете, можно будет просто завести массив фабрик и обращаться к ним по типу:
bill_factories[type_of_bill].createBill()

Но для этого лучше иметь как раз абстрактную фабрику с функцией createBill и от неё наследовать остальные фабрики, не изменяя название функции

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +    CreditBill newbill;
не соблюдается нейминг - в аргументах snake case, а в названии переменных _ куда-то потерялись

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +  auto vec = ReadFileBDAccounts();
vec - плохое имя

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +void Bank::CheckBills(int account_id) {
printBills тогда уж

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +void AddOperInHis(std::string account_id, std::string oper_type, std::string bill_from, std::string bill_to, std::string amount_of_money) {
addOperationToHistory
Никаких сокращений

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +void Bank::CheckHistory(int account_id) {
printHistory
По идее эти функции все должны возвращать список строк, например, и специальный интерфейс возвращает их
Если у вас сайт, то почему это всё принтится непонятно куда, а не передаётся адекватно на фронт?

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +  }
Что тут произошло?

2024-04-15 21:44 UTC, ArtemyBobkov commented on Bank.cpp
> +// тестирование
пока сойдёт, на 3 итерации всё должно быть вынесено в отдельные файлы с тестами

2024-04-15 21:44 UTC, ArtemyBobkov commented on CreditBillFactory.cpp
> +  CreditBill newbill;
всё тот же нейминг

2024-04-15 21:44 UTC, ArtemyBobkov commented on DebitBillFactory.cpp
> +  std::cout << "У вас " << newbill.money << "$ на вашем дебетовом счете" << std::endl;
Зачем каждый раз выводить эту информацию при создании счёта?
В целях дебага - в принципе ок, к релизу надо будет убрать

2024-04-15 21:44 UTC, ArtemyBobkov commented on README.md
> +Реализована функциональность для просмотра истории операций по счетам, а также логика для выполнения переводов между счетами, добавляя глубину и полезность банковской системе.
Почему History пустые?

2024-04-15 21:44 UTC, ArtemyBobkov commented on bd_accounts.csv
> +0,Paxan,1777418103717652482,Pavel,Dranov,Pervomayskaya30k7,224423
Данные пользователей ни в коем случае не должны находиться в гите
Как учебный пример показать, что оно в целом работает - наверно ок

2024-04-15 21:44 UTC, ArtemyBobkov commented on curlpp/Easy.hpp
> +/*
Сторонние библиотеки не должны попадать в гит. gitignore в помощь

2024-04-15 21:44 UTC, ArtemyBobkov commented on web/app.py
> +def create_bill(username):
везде в питоне должны быть проставлены тайпинги на аргументы функций и возвращаемые значения. В идеале - вообще на все переменные

2024-04-15 21:44 UTC, ArtemyBobkov commented on web/app.py
> +            return "Ошибка при создании счета", 400
Нужно выбрасывать ошибку и как-то её обрабатывать (raise ...), а не возвращать какие-то строки

2024-04-29 16:08 UTC, RahatLukuum commented on Account.cpp
> +    std::cout << "Создан депозитный счёт" << std::endl;
fake в ифе вызывается функция, создающая счёт и если она работает корректно, то выполняется эта часть кода

2024-04-29 16:15 UTC, RahatLukuum commented on Bank.cpp
> +void Bank::CheckHistory(int account_id) {
сделаем на 3й итерации

2024-07-12 12:05 UTC, merged